services:
  app:
    image: dockerfreedesign
    ports:
      - 8080:8080
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://dockermysqldb:3306/freedesign
      SPRING_DATASOURCE_USER: admin
      SPRING_DATASOURCE_PASSWORD: nimda
    depends_on:
      - dockermysqldb

  dockermysqldb:
    image: mysql
    environment:
      DATABASE_HOST: docker-mysql
      DATABASE_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: freedesign
      MYSQL_USER: admin
      MYSQL_PASSWORD: nimda